Fix typo in error message

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -18,6 +18,6 @@ publish:
       then
         echo "Composer package created: $ResponseBody";
       else
-        echo "Compoer package creation failed, error $ResponseCode: $ResponseBody" >&2;
+        echo "Composer package creation failed, error $ResponseCode: $ResponseBody" >&2;
         exit 1;
       fi
